#stategy params
strategy_name: Cumulative
patterns_per_exp: 256
minibatch_size:  128

#model and training params
model_name: EfficientNet
num_classes: 200
lr: 0.001
hs: 250
momentum: 0.9
epochs: 50

#scenario params
scenario: imagenet
resized: not
balanced: not
number_of_samples_per_class: 500
scenario_type: domain_incremental


num_class_from_imagenet: 20
num_experiences: 40