#stategy params
strategy_name: LwF
patterns_per_exp: 256
minibatch_size:  128
lwf_alpha: [2]


softmax_temperature: 1
#model and training params
model_name: wide_VGG9
num_classes: 60
lr: 0.001
hs: 250
epochs: 20

#scenario params
scenario: short_mnist_omniglot_fmnist_svhn_cifar10_imagenet
resized: resized
balanced: balanced
number_of_samples_per_class: 500
scenario_type: task_incremental


num_class_from_imagenet: 10
num_experiences: 5