#stategy params
strategy_name: MAS
patterns_per_exp: 256
minibatch_size:  128
mas_lambda_reg: 1
alpha: 0.5

#model and training params
model_name: EfficientNet_NotPretrained
num_classes: 60
lr: 0.001
hs: 250
epochs: 50

#scenario params
scenario: short_imagenet_cifar10_svhn_fmnist_omniglot_mnist
resized: resized
balanced: balanced
number_of_samples_per_class: 500
scenario_type: task_incremental


num_class_from_imagenet: 10
num_experiences: 5