#stategy params
strategy_name: Naive
patterns_per_exp: 256
minibatch_size:  128

#model and training params
model_name: wide_VGG9
num_classes: 200
lr: 0.001
momentum: 0.9
hs: 250
epochs: 50

#scenario params
scenario: imagenet
resized: not
balanced: not
number_of_samples_per_class: 500
scenario_type: domain_incremental

